### ISSUE TITLE
Looping not working without max delay time

### ISSUE THREAD

**Issue by nmrcarroll** [trdischat/tweakplaylist#2]
If max delay time is left blank the track will not loop even if the repeat option is set to on.

Testing:
-Max=blank, Min=Blank does not loop
-Max=0, Min=Blank loops
-Max=blank, Min=0 does not loop
-Max=0, Min=0 loops

**Comment by trdischat** [comment]
I think I found the bug. Please test and let me know if it works now. Thanks.

**Comment by trdischat** [comment]
Not fixed yet.  I should be able to resolve this in a little while.

**Comment by trdischat** [comment]
I think I got it this time.  Give it a try.  Thanks.

**Comment by nmrcarroll** [comment]
Confirmed working as expected now. Thanks!
