### ISSUE TITLE
ReferenceError: trPatchLib is not defined

### ISSUE THREAD

**Issue by jonlunsford** [trdischat/tweakplaylist#3]
I've started getting this error when the module is loading, in Foundry 0.5.5:

```
foundry.js:2065 ReferenceError: trPatchLib is not defined
    at Function.randomizeSound (patchSound.js:44)
    at patchSound.js:79
    at Function._call (foundry.js:2062)
    at Function.callAll [as __furnace_original_callAll] (foundry.js:2022)
    at Function.callOriginalFunction (Patches.js:56)
    at Function.<anonymous> (Debug.js:33)
    at Game.setupGame (foundry.js:5262)
    at async Game._initializeGameView (foundry.js:5818)
    at async Game.initialize (foundry.js:5204)
```

I'm unable to find _where_ `trPatchLib` is defined in the first place. Is it in another module/library? Could this be a conflict issue with other modules? Any pointers with debugging would be greatly appreciated.

**Comment by trdischat** [comment]
The trPatchLib class is defined in patchlib.js, which should load this class long before it is called by randomizeSound. What version of the module are you running?

**Comment by jonlunsford** [comment]
hmm, ok. the version is `0.4.5.5`

**Comment by trdischat** [comment]
Sorry, but I cannot reproduce this error.  Have you tried turning off all other modules.  It looks like you might be running Furnace.

**Comment by jonlunsford** [comment]
Thanks! Yes, issue appears to be with other modules. I am running Furnace, I'll continue to troubleshoot my specific configuration.

**Comment by trdischat** [comment]
My apologies, Jon.  You were absolutely right.  I failed to include the patchlib.js file in the module manifest!  Fixed now.  Please let me know if you see more errors.  Thanks.

**Comment by jonlunsford** [comment]
Oh! I will updated then :) Fwiw, I have the playlist tweak option of Furnace disabled as well.
