### ISSUE TITLE
Importer imports but now songs appear in playlist folders in UI.

### ISSUE THREAD

**Issue by lafrancewarren** [trdischat/tweakplaylist#5]
I ran the importer with the latest version of Foundry VTT (0.7.9) and Playlist importer (1.5.5).  Now no songs appear under each playlist.
![playlist Importer Empty](https://user-images.githubusercontent.com/66744006/105401854-40a69300-5bec-11eb-8ceb-a239bfb7282c.png)

**Comment by lafrancewarren** [comment]
I deleted all the playlist and tried the import process again, same result.

**Comment by trdischat** [comment]
Wrong module.  This module does not import playlists.
