### ISSUE TITLE
Incompatibility with 0.8.6

### ISSUE THREAD

**Issue by patrickburk1988** [trdischat/tweakplaylist#6]
This module does not appear to function properly in Foundry version 0.8.6 running on Forge.

The "Hide Tracks" option has no apparent effect; the currently playing track continues to display in non-GM clients.

"Allow Random" does display the new options (Maximum Volume, Minimum Volume, Minimum Delay, Large File Streaming) in the "Create Sound" and "Edit Sound" dialogs. Only the volume sliders appear to do anything, however, and the effect appears to stop working randomly. Also, attempting to edit a sound clears all the dialog inputs.

The following error is thrown by the browser console upon joining the game (patchlib.js, line 26):
```javascript
Cannot patch function. It has wrong content at line  4  :  showPlaying: this._playingSoundsData.length > 0,  !=  let visible = game.playlists.entities.filter(p => isGM || p.sounds.some(s => s.playing)); 
 getData(options) {
    this._prepareTreeData(this.tree);
    return foundry.utils.mergeObject(super.getData(options), {
      playingSounds: this._playingSoundsData,
      showPlaying: this._playingSoundsData.length > 0,
      playlistModifier: AudioHelper.volumeToInput(game.settings.get("core", "globalPlaylistVolume")),
      ambientModifier: AudioHelper.volumeToInput(game.settings.get("core", "globalAmbientVolume")),
      interfaceModifier: AudioHelper.volumeToInput(game.settings.get("core", "globalInterfaceVolume")),
      volumeExpanded: this._volumeExpanded
    });
  }
```

**Comment by trdischat** [comment]
This module is completely incompatible with FVTT 0.8.x.  The entire audio engine changed after 0.7.x.  This module will **not** be updated for 0.8.x and will only remain to support older versions of FVTT.  The hidden tracks feature is separately available in the [Hidden Soundtracks](https://foundryvtt.com/packages/hiddensoundtracks) module.  I have submitted a feature request for inclusion of the audio randomizing functions in the Foundry core [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/4718).   You should consider upvoting the request to show Atropos your support for the idea.  I have also been talking to the author of the [SoundBoard](https://foundryvtt.com/packages/SoundBoard) module to try to get him interested in making a soundscape creation tool with lots of randomization options, either as part of the SoundBoard module or possibly as an entirely separate module.
