### ISSUE TITLE
Doesn't hide playlist in 0.8

### ISSUE THREAD

**Issue by dineshm72** [trdischat/tweakplaylist#7]
Playlists are still visible to players in 0.8.

![image](https://user-images.githubusercontent.com/2231877/127569177-94a96fa3-dc29-4f09-91d6-9b188ecec535.png)

Also, I don't really know what the loop delay is supposed to look like, UI wise.  If it has an UI components, I don't see them.  Does it just automatically start with delay and volume adjustments on loop?

**Comment by trdischat** [comment]
This module is not compatible with version 0.8 and will not be updated for anything past 0.7.9.  The Foundry audio system was fundamentally changed in version 0.8.x and this module would have to be completely rewritten from scratch.  If you just want to hide playlists from players, I recommend the [Hidden Soundtracks](https://foundryvtt.com/packages/hiddensoundtracks) module.  If you are interested in random delays and volume changes, you should express your support for this feature to be added to the [Soundscape](https://github.com/CDeenen/Soundscape/issues/5) module.

**Comment by dineshm72** [comment]
Thanks for the info, and the recommendation.  It may be helpful to include the info in the Readme, if you have the time and inclination.
